### ISSUE TITLE
"Background detail": Explain the game in a help menu

### ISSUE THREAD

**Issue by BrettWitty** [jimbonator/tads-cookbook#1]
### Problem

It can useful to tell new or returning players what the background for the game is: where the game is set or who the player character is. While this might be obvious from an `EXAMINE ME`, you might want to elaborate some more.

It'd be nice to have some initial hints to guide them in the right direction.

### Solution

Add a few game hints with permanently open goals so the hints on the backstory are always available:

```
TopHintMenu 'Hints';

+ HintMenu 'The Basics';

++ Goal 'Where am I?'
    ['You are in the TADS Cookbook kitchen.']
    openWhen = true
;

++ Goal 'Who am I?'
    ['You are the AFGNCAAP: the ageless, faceless, gender-neutral, culturally-ambiguous adventure person.']
    openWhen = true
;
```

To get to this menu, a player needs to type `HINT` (and then again after the warning). To disable the warning, you can do so at game initialization:
```
InitObject
    execute() {
        sessionHintStatus.hintWarning = true;
        gameHintStatus.hintWarning = true;
    }
```

To remap `HELP` to `HINT`:
```
DefineIAction(Help)
    execAction() {
        if (gHintManager != nil)
            gHintManager.showHints();
        else
            mainReport(gLibMessages.hintsNotPresent);
    }
;

VerbRule(Help)
    'help'
    : HelpAction
    verbPhrase = 'show/showing help'
;
```

**Comment by jimbonator** [comment]
It's up!  Thanks for your patience.
